### ISSUE TITLE
Incorrect management of some addresses (about 5%) leads to ignoring the event

### ISSUE THREAD

**Issue by csauge** [trouver-une-fresque/trouver-une-fresque#12]
Cases to manage are all "Rejecting" with "address" keyword.
Exemples for billetweb only:
- Rejecting records: address is too long (5 parts): HOBA, Parc Martin Luther King, 44 Rue Bernard Buffet, 75017 Paris, France
- Rejecting record: empty address: Ferme du parc du Héron - Villeneuve d'ascq
- Rejecting record: empty address: Espace Multiburo - 1 Cr du Havre 75008 PARIS
- Rejecting record: empty address: Online
- Rejecting records: address is too long (5 parts): La Melting Coop, épicerie et café participatifs, Cours Emile Zola, Villeurbanne, Fr
- Rejecting record: empty address: Salle des fêtes de Ramonville Rue Joliot Cur
- Rejecting record: empty address: Le LAC de Sèvres 12 rue Lecointre 92310 Sèvres
- Rejecting record: empty address: La BOM 2 rue Girard 93100 Montreuil
- Rejecting record: empty address: Les Canaux 6 quai de la Seine - 75019 Paris
- Rejecting records: address is too long (5 parts): Canopy, l'art de se réunir!, Rue Négrier, Lille, France

Nevertheless, i think there would be better to manage the raw full address (for all kind of event: billetweb, glide, eventbrite...) directly in `utils/readJson.py`

**Comment by thomasguillory** [comment]
Hello Christophe 👋 
I'm starting to look in this project as well on my side :)

I see that the address parser is custom in this project and the rules are quite strict (explicited in TUTORIAL.md).

https://github.com/trouver-une-fresque/trouver-une-fresque/blob/b013e88a662113204a1616de849f308ae9601126/scraper/billetweb.py#L306-L330

I think it's worth adding a 3rd-party address parser here (eg. the lib fraddress). Not sure what's the best in python ? It would need to support at least FR addresses, but the wider the scope is the better (knowing that FDC has international events).

**Comment by csauge** [comment]
Actually this code needs to be enhanced indeed. Nevertheless the code already use (a few line after) the API of https://adresse.data.gouv.fr/ but it does not work well when there is the name of the location (ex: Bar les Canaux) before the address. So there is a need to isolate the name of the location first, but the main issue is that there are many different way to write an address (commas, hyphen, with or without country, with or without location...)

**Comment by thomas-bouvier** [comment]
Thank you for your suggestions. At first sight, I think I would prefer relying on a 3rd-party parser (leveraging NLP like https://github.com/alannadevgen/french-address-matching?) and reinjecting the result into the national address API.

Another approach would be to flood the API with address variants, but would that be reliable?

**Comment by csauge** [comment]
> Thank you for your suggestions. At first sight, I think I would prefer relying on a 3rd-party parser (leveraging NLP like https://github.com/alannadevgen/french-address-matching?) and reinjecting the result into the national address API.
> 
> Another approach would be to flood the API with address variants, but would that be reliable?

Hard say what is the best way.
National address API does not work correctly sometimes.
And i cannot find a good free 3rd-party parser.
Nevertheless, i think there would be better to manage the raw full address (for all kind of event: billetweb, glide, eventbrite...) directly in utils/readJson.py instead of doing stuff in each billeteries

**Comment by thomas-bouvier** [comment]
A solution has been implemented in https://github.com/trouver-une-fresque/trouver-une-fresque/pull/27.
