### ISSUE TITLE
Billetterie HelloAsso

### ISSUE THREAD

**Issue by Manudad** [trouver-une-fresque/trouver-une-fresque#2]
Bonjour,
Est-ce qu'il est envisagé d'importer les ateliers de HelloAsso ? Ou est-ce qu'il y a une incompatibilité informatique ?

Merci 
Manu

**Comment by thomas-bouvier** [comment]
Bonjour @Manudad,

Merci pour ton message. En soi, il n'y a pas de barrière technique empêchant d'extraire les informations d'HelloAsso.

Nous devons cependant nous assurer que les évènements qui y sont publiés ne fassent pas doublon avec une autre plateforme de billetique. Pour l'instant, nous avons fait au plus simple en considérant que chaque type d'atelier avait une et une seule plateforme pour réserver.

J'ai bien lu ton email et j'y répondrai dans quelques jours pour discuter de votre cas :)
