### ISSUE TITLE
Move address parsing for glide, eventbrite, fdc, fec to readJson.py

### ISSUE THREAD

**Issue by csauge** [trouver-une-fresque/trouver-une-fresque#29]
Following #12 (for billetweb), Use address parsing for all other inputs (glide, eventbrite, fdc, fec) by :
- Using directly readJson.py get_address() as billetweb does
- Remove the former get_address_data and strip_zip_code useless functions

**Comment by thomas-bouvier** [comment]
Fixed in https://github.com/trouver-une-fresque/trouver-une-fresque/commit/e4443ccc27074c653c7455478159d30af3a2e87d, as part of the transition to OSM data.
