### ISSUE TITLE
Add support for multi-events on Billetweb

### ISSUE THREAD

**Issue by thomas-bouvier** [trouver-une-fresque/trouver-une-fresque#3]
Some associations publish multiple events per page on Billetweb:
- `Fresque de la Biodiversité`
- `Fresque du Sexisme`
- `Fresque du Numérique`
- `Fresque des Nouveaux Récits`

We should think of supporting these.

**Comment by polomarcus** [comment]
Salut @thomas-bouvier ,

Est ce que tu sais comment on pourrait t'aider pour coder cette partie ? Si tu me montres/conseilles les quelques endroits à modifier (code+test).

_Sans [CI github](https://docs.github.com/fr/actions/automating-builds-and-tests/building-and-testing-python) ou d'image docker pour lancer le projet rapido, je crains de me perdre un peu dans le méandre du code :see_no_evil:_ 

Paul 

---
**Mes notes en brut pour la Fresque du numérique** : 
:one: Adresse à scrapper : https://www.billetweb.fr/multi_event.php?multi=11442&color=4285f4&language=fr

Le code en question a l'air de correspondre ici : https://github.com/trouver-une-fresque/trouver-une-fresque/blob/main/scraper/billetweb.py#L130-L131

Je vois bien une evolution en créant une fonction externe `parse_event` qui serait appelée :
```
if "https://www.billetweb.fr/multi_event.php?&multi" not in link:
    # parse_unique_event
else
   # parse_multi_event(link)
```


:two: Scrapper chaque sous lien, par exemple Hérault - 34 : https://www.billetweb.fr/herault-34-atelier-fresque-du-numerique&multi=11442&language=fr&color=4285f4&parent=1&language=fr&color=4285f4

**Comment by Marc-AntoineA** [comment]
Où en êtes vous @thomas-bouvier et @polomarcus ? Besoin d’aide ?

Pour la Fresque du Sexisme, si on clique sur un événement puis on clique sur "choisir un autre événement", l’url change de https://www.billetweb.fr/pro/fresque-du-sexisme à https://www.billetweb.fr/multi_event.php?&multi=27112, qui me semble équivalente à celle de la Fresque du numérique. Il me semble donc qu’on pourrait se baser sur l’url pour le scrapping.

**Comment by polomarcus** [comment]
Salut @Marc-AntoineA je suis toujours à 0 malheureusement faute de temps.

Tu te sens de prendre en main la feature ?

**Comment by thomas-bouvier** [comment]
C'est l'occasion de s'y essayer :) Tu devrais t'en sortir en reprenant du code existant.

Je n'y connais pas grand chose non plus. Si vous avez des idées pour améliorer la robustesse/lisibilité du code, je suis preneur !
