### ISSUE TITLE
Ajout des ateliers de la Fresque de la Finance sur le site Trouver une fresque

### ISSUE THREAD

**Issue by Celga13** [trouver-une-fresque/trouver-une-fresque#32]
Bonjour, 

Les ateliers Fresque de la Finance n'apparaissent pas dans "Trouver une fresque" pourtant j'ai l'impression que nous respectons tous les critères mentionnés pour une billetterie sur BilletWeb. 
[Lien](https://www.billetweb.fr/multi_event.php?&multi=34683) vers notre billetterie.
Du coup, je me permets de vous envoyer un petit message ;-)
Merci d'avance pour votre réponse.
Céline pour la Fresque de la Finance.

**Comment by csauge** [comment]
En effet, vous devriez avoir tout ce qu'il faut, il faudrait juste que l'on traite un ajout de lien vers cette page (en backend et frontend) et aussi votre logo. On attend jsute qu'une bonne âme bénévole traite la demande :)

**Comment by Celga13** [comment]
merci beaucoup pour votre réponse :-)
je vais attendre alors ;-)
Voici le lien vers la billeterie : https://www.billetweb.fr/pro/fresquedelafinance
et j'ai mis en PJ notre logo.
![logo FDF resize 200px](https://github.com/trouver-une-fresque/trouver-une-fresque/assets/163430203/085e39de-7cd8-4a02-805c-aec3d79cf755)
bonen journée.

**Comment by TimotF** [comment]
La fresque de la finance a été ajoutée sur le site

**Comment by Celga13** [comment]
Merci beaucoup :-)
