### ISSUE TITLE
Mes événements n'apparaissent pas dans trouverunefresque.org

### ISSUE THREAD

**Issue by baptisteaden** [trouver-une-fresque/trouver-une-fresque#34]
Bonjour,

J'ai attendu 4 jours et vérifié si les événements étaient correctement formattés, mais je ne parviens pas à trouver de problème ! Qu'en pensez-vous ?

Les adresses des événements :

https://www.eventbrite.com/e/billets-2tonnes-atelier-a-vitre-35500-875921142717?aff=odcleoeventsincollection&keep_tld=1

https://association.climatefresk.org/training_sessions/e557a515-449a-4dc2-9343-f37b90e672a0/show_public?language=fr&tenant_token=36bd2274d3982262c0021755

https://association.climatefresk.org/training_sessions/045a4cbd-781e-4ed3-a044-eacce49301ab/show_public?language=fr&tenant_token=36bd2274d3982262c0021755

Merci d'avance !

**Comment by thomas-bouvier** [comment]
Hello @baptisteaden,

Ces ateliers apparaissent bien avec la dernière MAJ de la plateforme :)

Les données sont mises à jours tous les 4-7 jours. Cette fréquence augmentera dans le futur.

**Comment by baptisteaden** [comment]
Hello Thomas,

Okay super, je pensais que c'était 4 jours max pardon !

Merci de ton aide !
Bonne fin de journée :)
