### ISSUE TITLE
Atelier 2 tonnes introuvable

### ISSUE THREAD

**Issue by LiseEmma** [trouver-une-fresque/trouver-une-fresque#35]
Bonjour
un atelier 2 tonnes a été publié dans l'agenda du site de l'Atelier du Déclic, à la date du 11 juin, à l'Oasis Fontmarie, à Castries.
agenda-atelierdudeclic.glide.page/dl/d0a5f4/m/6d8d15/r/qDTNIG0rLma9amHJKVBc

J'ai vérifié, les informations semblent correctement saisies or cet atelier ne remonte pas avec votre moteur de recherche.

Pouvez-vous nous indiquer quel est le problème, voire le résoudre ?
Merci.
Lise

**Comment by thomas-bouvier** [comment]
Bonjour @LiseEmma,

Une condition pour apparaître sur notre plateforme est de faire figurer les ateliers sur leur billetterie officielle. Dans votre cas, il faudrait que votre atelier apparaisse [ici](https://www.eventbrite.fr/o/2-tonnes-29470123869) pour être recensé.

**Comment by LiseEmma** [comment]
Bonjour Thomas

ok, merci pour la précision. C'est une association tiers-lieu qui organise l'atelier et qui, du coup, a ouvert sa propre billetterie. Je vais leur signaler pour une prochaine fois, afin d'assurer une meilleure visibilité.

________________________________
De : Thomas Bouvier ***@***.***>
Envoyé : dimanche 2 juin 2024 20:01
À : trouver-une-fresque/trouver-une-fresque ***@***.***>
Cc : LiseEmma ***@***.***>; Mention ***@***.***>
Objet : Re: [trouver-une-fresque/trouver-une-fresque] Atelier 2 tonnes introuvable (Issue #35)


Bonjour @LiseEmma<https://github.com/LiseEmma>,

Une condition pour apparaître sur notre plateforme est de faire figurer les ateliers sur leur billetterie officielle. Dans votre cas, il faudrait que votre atelier apparaisse ici<https://www.eventbrite.fr/o/2-tonnes-29470123869> pour être recensé.
