### ISSUE TITLE
Fresque du Bénévolat non référencée sur la plateforme

### ISSUE THREAD

**Issue by moniqueb91** [trouver-une-fresque/trouver-une-fresque#37]
Bonjour, 
Tout d'abord, merci pour la plateforme que vous avez créé !

Nous voulons faire référencer la fresque sur votre site, nous avons respecté les règles que vous avez indiqué (une seule date + faire figurer mention "obtenir des billets"), mais nos fresques ne sont toujours pas visibles sur la plateforme.  

On utilise Eventbrite, voici le lien de notre fresque : https://www.eventbrite.fr/e/fresque-du-benevolat-a-la-cite-fertile-pantin-1611-tickets-1053125519779

Pouvez-vous nous aider ? 

Merci d'avance !

**Comment by thomas-bouvier** [comment]
Bonjour @moniqueb91,

C'est bien pris en compte, j'intégrerai vos évènements prochainement.

**Comment by moniqueb91** [comment]
Bonjour, j'espère que vous allez bien.

Sauf erreur de ma part, notre fresque (
https://www.eventbrite.com/e/fresque-du-benevolat-a-la-cite-fertile-pantin-1611-tickets-1053125519779?aff=ebdssbdestsearch&keep_tld=1)
n'est toujours pas visible sur votre site, il y a t-il des étapes que nous
devons suivre pour que ce soit le cas ?

Merci d'avance

Le lun. 28 oct. 2024 à 18:47, Thomas Bouvier ***@***.***> a
écrit :

**Comment by thomas-bouvier** [comment]
Bonjour,

Nous devons avoir la garantie que cette page ne listera que des Fresques du Bénévolat https://www.eventbrite.fr/o/jeveuxaidergouvfr-77010082313. Est-ce prévu ?

**Comment by moniqueb91** [comment]
Bonjour, oui, c'est le cas

Le mer. 13 nov. 2024 à 19:13, Thomas Bouvier ***@***.***> a
écrit :

**Comment by thomas-bouvier** [comment]
La Fresque du Bénévolat sera référencée lors de la prochaine MAJ.
