### ISSUE TITLE
Ajouter les ateliers de la Fresque de la Forêt à Trouver une fresque

### ISSUE THREAD

**Issue by loraineba** [trouver-une-fresque/trouver-une-fresque#4]
Bonjour, je découvre votre outil et aurais aimé savoir comment ajouter les ateliers de la Fresque de la Forêt à Trouver une fresque, sachant que nous utilisons la billetterie Weezevent ?

Merci par avance pour votre retour,

Loraine

**Comment by thomas-bouvier** [comment]
Bonjour @loraineba,

Pour intégrer les ateliers Fresque de la Forêt, nous devons améliorer notre robot pour extraire les informations de la billetterie Weezevent (ce qui est tout à fait possible). Seulement, la vue Calendrier présente sur [cette page](https://my.weezevent.com/fresque-de-la-foret-numerique-all4trees) complexifie les choses.

Y a-t-il une fonctionnalité, sur la billetterie Weezevent, permettant d'afficher une liste énumérant les prochaines ateliers ?

**Comment by loraineba** [comment]
Bonjour Thomas,

Merci pour votre retour. A ma connaissance, non, mais je vais demander à Weezevent car ce serait utile en effet d'avoir cette page sur leur site. Je vous tiens au courant.

Bonne journée à vous

**Comment by thomas-bouvier** [comment]
Bonjour @loraineba,

Désolé pour le délai de réponse, c'est un oubli de ma part.

Il n'y a pas d'impossibilité technique à proprement parler. Seulement, la complexité de tels widgets "calendrier" induit des temps de développement et de maintenance supplémentaires.

Je me rends compte en écrivant ce message qu'une liste des évènements est disponible à [cette addresse](https://all4trees.org/agir/fresque-foret/evenements/), ce qui nous facilitera la tâche. Je ne peux pas vous donner de date pour le moment, mais j'ai ajouté l'intégration de la Fresque de la Forêt à notre feuille de route.

Merci !

**Comment by loraineba** [comment]
Bonjour Thomas,

Je me permets de répondre à la place de Loraine, dont le contrat à l’association s’est récemment terminé. Je prends le relais sur ce dossier 😊.

C’est noté pour les difficultés techniques. Loraine m’avait expliqué, sauf erreur de ma part, qu’elles étaient liées au fait que nos billetteries sont générées sur Weezevent, qui n’est pas le logiciel auquel vous êtes habitué ?

Je vous confirme que la liste de nos ateliers est mise en ligne sur le site et est tenue à jour. N’hésitez pas si vous avez besoin de plus d’informations !

Très bonne journée,

***@***.***<https://all4trees.org/>
Solen MENGUY-TROUVE
Responsable du développement
P. : +33 (0) 6 59 89 78 45
www.all4trees.org
Rejoignez la communauté
[Facebook]<https://www.facebook.com/all4trees/>
[Twitter]<https://twitter.com/ll4trees>
[LinkedIn]<https://www.linkedin.com/company/all4trees/>


De : Thomas Bouvier ***@***.***>
Envoyé : mardi 21 novembre 2023 18:52
À : trouver-une-fresque/trouver-une-fresque ***@***.***>
Cc : loraine ***@***.***>; Mention ***@***.***>
Objet : Re: [trouver-une-fresque/trouver-une-fresque] Ajouter les ateliers de la Fresque de la Forêt à Trouver une fresque (Issue #4)


Bonjour @loraineba<https://github.com/loraineba>,

Désolé pour le délai de réponse, c'est un oubli de ma part.

Il n'y a pas d'impossibilité technique à proprement parler. Seulement, la complexité de tels widgets "calendrier" induit des temps de développement et de maintenance supplémentaires.

Je me rends compte en écrivant ce message qu'une liste des évènements est disponible à cette addresse<https://all4trees.org/agir/fresque-foret/evenements/>, ce qui nous facilitera la tâche. Je ne peux pas vous donner de date pour le moment, mais j'ai ajouté l'intégration de la Fresque de la Forêt à notre feuille de route.

Merci !
